### ISSUE TITLE
Executor should not pass its configuration to a task

### ISSUE THREAD

**Issue by janisz** [allegro/mesos-executor#84]
The executor is configured with `ALLEGRO_EXECUTOR_*` env variable. This variable might contains confidential information e.g. `ALLEGRO_EXECUTOR_CONSUL_TOKEN`. A task should not have access to executor configuration. 

The problem is beouse executor copies its wnvironment and merge it with task env variables [`func combineExecutorAndTaskEnv(env []string, mesosEnv *mesos.Environment) []string`](https://github.com/allegro/mesos-executor/blob/v0.11.4/command.go#L174)

**Comment by medzin** [comment]
It is worth noting that variables from TaskInfo are already set in the executor environment, so we do not have to set them but just clean the executor environment and copy it to command.
